steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: 'data.handler'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'data.handler'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/data-handler', '-f', 'Dockerfile', '.']

images:
  - 'gcr.io/$PROJECT_ID/data-handler'
timeout: 1200s