steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: 'data.handler'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'data.handler'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/data-handler', '-f', 'Dockerfile', '.']
    # Push image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/data-handler
    # Configure a kubectl workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
    #   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #  dir: 'data.handler'
    #  entrypoint: 'bash'
    #  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

  # Deploy with Helm
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - data-handler
      - ./kubernetes
      - --set
      - image.repository=gcr.io/$PROJECT_ID/data-handler,image.tag=latest
      - -f
      - ./kubernetes/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=false
      - TILLER_NAMESPACE=kube-system
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: gke-cluster

#images:
#  - 'gcr.io/$PROJECT_ID/data-handler'
#timeout: 1600s