steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: 'data.handler'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'data.handler'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/data-handler', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

images:
  - 'gcr.io/$PROJECT_ID/data-handler'
timeout: 1600s