steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: '$_WORK_DIR_NAME'
  - name: 'gcr.io/cloud-builders/docker'
    dir: '$_WORK_DIR_NAME'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  # push image to Google Cloud Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
  # deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--expose=8080'
timeout: 1200s
options:
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _K8S_APP_NAME: data-handler
  _IMAGE_NAME: data-handler
  _WORK_DIR_NAME: data.handler
  _GKE_LOCATION: us-central1-a
  _GKE_CLUSTER: gke-cluster


    #   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #  dir: 'data.handler'
  #  entrypoint: 'bash'
  #  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
#images:
#  - 'gcr.io/$PROJECT_ID/data-handler'
#timeout: 1600s