steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: 'data.handler'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'data.handler'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/data-handler:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  # push image to Google Cloud Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/data-handler:$COMMIT_SHA
  # deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/data-handler:$COMMIT_SHA
      - --location=$_CUSTOM_REGION
      - --cluster=$_CUSTOM_CLUSTER
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: gke-cluster


    #   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #  dir: 'data.handler'
  #  entrypoint: 'bash'
  #  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
#images:
#  - 'gcr.io/$PROJECT_ID/data-handler'
#timeout: 1600s